# Generated by Django 5.2 on 2025-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('bus', 'Bus Route'), ('train', 'Train Map'), ('campus', 'Campus Map'), ('other', 'Other')], default='other', max_length=20)),
                ('image', models.ImageField(upload_to='maps/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
