# Generated by Django 5.2 on 2025-06-20 08:02

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None)),
                ('opening_time', models.TimeField(default='07:00')),
                ('closing_time', models.TimeField(default='22:00')),
                ('image', models.ImageField(upload_to='canteen_images/')),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('canteen_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('slug', autoslug.fields.AutoSlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Main Meal', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, null=True, unique=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='Orderfood.canteen')),
            ],
        ),
    ]
