# Generated by Django 5.2 on 2025-06-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orderfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='delivery_time',
            field=models.CharField(default='20 min', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='delivery_time',
            field=models.CharField(default='20 min', max_length=15, null=True),
        ),
    ]
