# Generated by Django 5.2 on 2025-06-20 08:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orderfood', '0002_canteen_delivery_time_menuitem_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
