# Generated by Django 5.2 on 2025-06-20 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orderfood', '0003_alter_canteen_slug_alter_menuitem_slug'),
        ('Webusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(blank=True, max_length=50, null=True)),
                ('item_price', models.IntegerField(blank=True, null=True)),
                ('item_quantity', models.PositiveIntegerField(default=1)),
                ('item_slug', models.SlugField(default=None, unique=True)),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Webusers.users')),
            ],
        ),
    ]
