# Generated by Django 5.2 on 2025-06-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orderfood', '0005_orderdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
