# Generated by Django 5.2 on 2025-06-26 10:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orderfood', '0006_delete_orderdetails'),
        ('Webusers', '0009_alter_userprofile_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('items', models.TextField(help_text='Comma-separated list of item names')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('order_type', models.CharField(choices=[('Delivery', 'Delivery'), ('Pickup', 'Pickup')], max_length=20)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online')], max_length=20)),
                ('order_status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Ready', 'Ready'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=30)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webusers.users')),
            ],
        ),
    ]
