# Generated by Django 5.2 on 2025-06-19 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_calendar', '0001_initial'),
        ('Webusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webusers.users'),
        ),
    ]
