# Generated by Django 5.2 on 2025-06-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
    ]
