# Generated by Django 5.2 on 2025-06-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0002_alter_assignment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
    ]
