# Generated by Django 5.2 on 2025-06-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0002_remove_assignment_user'),
        ('Webusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Webusers.users'),
        ),
    ]
