# Generated by Django 5.2 on 2025-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0003_remove_assignment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_start',
            field=models.DateTimeField(),
        ),
    ]
