# Generated by Django 5.2 on 2025-06-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignments', '0004_assignment_link_assignment_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(default='General', max_length=255, null=True),
        ),
    ]
