# Generated by Django 5.2 on 2025-06-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Arriving', 'Arriving'), ('On Route', 'On Route'), ('Delayed', 'Delayed'), ('On Time', 'On Time')], max_length=50)),
                ('arrival_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=20)),
                ('arrival_time', models.CharField(max_length=20)),
                ('frequency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Arriving', 'Arriving'), ('Delayed', 'Delayed'), ('On Time', 'On Time')], max_length=50)),
                ('arrival_time', models.CharField(max_length=20)),
            ],
        ),
    ]
