# Generated by Django 5.2 on 2025-06-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route',
        ),
        migrations.AddField(
            model_name='bus',
            name='departure_time',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='from_location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='to_location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='from_location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='to_location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='departure_time',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='from_location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='to_location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='arrival_time',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(blank=True, choices=[('Arriving', 'Arriving'), ('On Route', 'On Route'), ('Delayed', 'Delayed'), ('On Time', 'On Time')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='arrival_time',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='bus_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='departure_time',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='frequency',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='arrival_time',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='platform',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='status',
            field=models.CharField(blank=True, choices=[('Arriving', 'Arriving'), ('Delayed', 'Delayed'), ('On Time', 'On Time')], default=None, max_length=50, null=True),
        ),
    ]
