# Generated by Django 5.2 on 2025-06-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportation', '0002_remove_bus_route_bus_departure_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='days_running',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='frequency',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
