# Generated by Django 5.2 on 2025-06-19 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('founded', models.DateField(blank=True, null=True)),
                ('president', models.CharField(blank=True, max_length=100)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='club_banners/')),
                ('description', models.TextField(help_text='You can use HTML for formatting')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='club_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='Clubs.club')),
            ],
        ),
    ]
