# Generated by Django 5.2 on 2025-06-27 17:04

import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Webusers', '0009_alter_userprofile_roll_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCanteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canteen_name', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None)),
                ('image', models.ImageField(upload_to='canteen_images/')),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('canteen_id', models.CharField(max_length=50, unique=True)),
                ('opening_time', models.TimeField(default='07:00')),
                ('closing_time', models.TimeField(default='22:00')),
                ('email', models.EmailField(max_length=254)),
                ('delivery_time', models.CharField(default='20 min', max_length=15, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='canteen_name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=125)),
                ('email', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('items', models.JSONField(default=list)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('order_type', models.CharField(choices=[('Delivery', 'Delivery'), ('Pickup', 'Pickup')], max_length=20)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online')], max_length=20)),
                ('order_status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Ready', 'Ready'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=30)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Webusers.users')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Restaurant.registercanteen')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Main Meal', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('delivery_time', models.CharField(default='20 min', max_length=15, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='Restaurant.registercanteen')),
            ],
        ),
        migrations.AddField(
            model_name='registercanteen',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_owner', to='Restaurant.registerowner'),
        ),
    ]
