# Generated by Django 5.2 on 2025-06-27 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_alter_orderdetails_canteen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='canteen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Restaurant.registercanteen'),
        ),
    ]
