# Generated by Django 5.2 on 2025-06-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_alter_orderdetails_canteen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='canteen',
            field=models.ForeignKey(default='/menu_items/set-vector.jpg', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='Restaurant.registercanteen'),
        ),
    ]
