# Generated by Django 5.2 on 2025-06-28 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_alter_menuitem_canteen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='canteen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='Restaurant.registercanteen'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='/menu_items/set-vector.jpg', upload_to='menu_images/'),
        ),
    ]
