# Generated by Django 5.2 on 2025-06-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webusers', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_clubs', to='Webusers.users'),
        ),
    ]
