# Generated by Django 5.2 on 2025-06-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webusers', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='members',
        ),
    ]
